Usability security
BME-MIT-IET/iet-hf2021-meg-iet pull request #10
Opened 2021-05-15 14:42 UTC by Lacieee

Testing security and usability of the CSV2RDF library.

2021-05-15 14:58 UTC, jcsenge requested changes

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +*A teszt célja kimeríteni a szoftver esetleges biztonsági réseit, és potenciális hibalehetőségeit*
A vessző nem szükséges a 'réseit' után :D

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +* Beférközési teszt
"Beférkőzési" ?

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +Ezek közül mi a sebezhetőségi vizsgáltra koncentráluk legfőképp, továbbá a manuálisan is végezhető biztonsági auditálásra. Elsőként a SonarQube eszköz által észlet biztonsági hibákat detektáltuk, mel
"észlet" -> "észlelt"?

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +A CSV2RDF egy egyszerű, és könnyen kezelhető könyvtár. A neve önmagában sokatmondó, és lefedi a képességei igen szűk metszetét. A rendszer hatékonysága egy külön dokumentációban kerül részletes kifej
"...és lefedi a képességei igen szűk metszetét." Mire gondolsz? A kevés funkcióra vagy arra hogy a név nem fedi le hogy mit csinál a program/a program funciói közül csak kevésre utal közvetlenül ? Ha az utóbbi, akkor nem épphogy "és lefedi a program szűk képességeinek összességét"? (Ez csak egy javaslat, nem ragaszkodom hozzá, csak számomra nem volt egyértelmű mire gondolunk)

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +Tapasztalataink alapján a rendszer tervezése során - az egyszerűsége révén - öszpontosított a pontosságra, és tesztjeink során kiderült, hogy jól alkalmazkodik nem várt felhasználói viselkedésekhez,
"A rendszer tervezése során öszpontosított a pontosságra"?
Nem a tervezők **összpontosítottak**?

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +Tapasztalataink alapján a rendszer tervezése során - az egyszerűsége révén - öszpontosított a pontosságra, és tesztjeink során kiderült, hogy jól alkalmazkodik nem várt felhasználói viselkedésekhez,
A hiba nem túl informatív vagy a hibaüzenet ?

2021-05-15 14:58 UTC, jcsenge commented on doc/usability-security.md
> +Ezen tapasztalatok során arra jutottunk, hogy kezelni, valamint használni a könyvtárat nem okoz nehézségeket, és a rövid és tömör dokumentáció elégnek bizonyul. A jövőbeni használhatóság érdekében mi
mindenképp

2021-05-15 15:06 UTC, dseben commented on doc/usability-security.md
> +Ezek közül mi a sebezhetőségi vizsgáltra koncentráluk legfőképp, továbbá a manuálisan is végezhető biztonsági auditálásra. Elsőként a SonarQube eszköz által észlet biztonsági hibákat detektáltuk, mel
vizsgáltra -> vizsgálatra typo

2021-05-15 15:11 UTC, varszegik requested changes

2021-05-15 15:11 UTC, varszegik commented on doc/usability-security.md
> +A CSV2RDF egy egyszerű, és könnyen kezelhető könyvtár. A neve önmagában sokatmondó, és lefedi a képességei igen szűk metszetét. A rendszer hatékonysága egy külön dokumentációban kerül részletes kifej
vagy szűk képesságeinek halmazát?

2021-05-15 15:11 UTC, jcsenge commented on doc/usability-security.md
> +Ezen tapasztalatok során arra jutottunk, hogy kezelni, valamint használni a könyvtárat nem okoz nehézségeket, és a rövid és tömör dokumentáció elégnek bizonyul. A jövőbeni használhatóság érdekében mi
Typora gondoltam "mindenkép" -> "mindenképp"

2021-05-15 15:12 UTC, varszegik requested changes

2021-05-15 15:12 UTC, varszegik commented on doc/usability-security.md
> +Ezek közül mi a sebezhetőségi vizsgáltra koncentráluk legfőképp, továbbá a manuálisan is végezhető biztonsági auditálásra. Elsőként a SonarQube eszköz által észlet biztonsági hibákat detektáltuk, mel
megjelneítésére typo

2021-05-15 16:11 UTC, eperst requested changes
Nice work.
Pls merge performance test and stress branches before merging all to main. Consider merging documentation with performance test & stress test docs.

2021-05-15 17:02 UTC, jcsenge approved these changes

2021-05-15 17:04 UTC, eperst approved these changes

2021-05-15 17:22 UTC, dseben approved these changes

2021-05-16 09:46 UTC, varszegik approved these changes

2021-05-16 09:47 UTC, merged