Refactor/dedicated exceptions
BME-MIT-IET/iet-hf2021-meg-iet pull request #12
Opened 2021-05-15 15:24 UTC by eperst

Fix for Issue #8 

All exceptions logged.
Basic feedback to standard output for FileNotFoundException.

2021-05-15 15:25 UTC, Lacieee approved these changes

2021-05-15 17:21 UTC, dseben approved these changes

2021-05-16 09:39 UTC, jcsenge approved these changes

2021-05-16 09:51 UTC, varszegik requested changes

2021-05-16 09:51 UTC, varszegik commented on src/com/complexible/common/csv/CSV2RDF.java
> +		} catch (Exception e) {
this is wrong as this would result in fatal errors being handled, program continues to run and prints "Converted %,d rows to %,d triples%n"

2021-05-16 09:51 UTC, varszegik commented on src/com/complexible/common/csv/CSV2RDF.java
> +			System.out.printf("File not found%n");
please merge origin/main and replace System.out prints with logger.logs

2021-05-16 10:23 UTC, varszegik requested changes

2021-05-16 10:23 UTC, varszegik commented on src/com/complexible/common/csv/CSV2RDF.java
> +			LOGGER.log(Level.SEVERE, io.getMessage());
this applies to all exceptions, program should stop here

2021-05-16 10:23 UTC, varszegik commented on src/com/complexible/common/csv/CSV2RDF.java
> +			throw new UnsupportedRDFormatException(f);
throw f;

2021-05-16 10:23 UTC, varszegik commented on src/com/complexible/common/csv/CSV2RDF.java
> +			LOGGER.log(Level.SEVERE, f.getMessage());
also should stop here

2021-05-16 11:08 UTC, varszegik approved these changes

2021-05-16 11:28 UTC, merged